### ISSUE TITLE
Autocommand error when opening cheddar file

### ISSUE THREAD

**Issue by DJMcMayhem** [cheddar-lang/cheddar.vim#1]
I installed this through vim-plug, and it goes great as long as I manually call

```
:se ft=cheddar
```

If I just edit a cheddar file, I get

```
Error detected while processing BufRead Auto commands for "*.cheddar":
E20: Mark not set
```

**Comment by vihanb** [comment]
Fixed in 7c719ee1e3c54a289b21cf488dff50f91250b8f5
